### ISSUE TITLE
Get some test-drivers aboard

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/xml-security#42]
Now that we have finished decoupling from `xmlseclibs` and tagged a first stable release for this library, it would be good to know if it really is as great as we believe it is. I'll be using this issue to tag random people with different (non-SAML related) use-cases and ask them whether they're interested to try it.

**Comment by tvdijen** [comment]
@big89 I couldn't help but notice the issues you are having with `xmlseclibs`.. Would you be interested in trying this library instead?

**Comment by big89** [comment]
Thanks @tvdijen for highlighting me about this library.

Further, we need to sign xml for e-sign functionality. Let me know which example we could try with.

Thanks!

**Comment by tvdijen** [comment]
All the necessary information should be in the [README](https://github.com/simplesamlphp/xml-security#signature-api). You would have to model your XML-structure into a PHP-class (MyObject in the example) and implement some abstract methods from the interfaces.

Here is an example of such a class that we use for our unit tests:
https://github.com/simplesamlphp/xml-security/blob/master/tests/XML/CustomSignable.php

**Comment by tvdijen** [comment]
Hi @big89 ! You have any feedback for us regarding this lib? We're very keen to hear!

**Comment by tvdijen** [comment]
@SharkMachine I couldn't help but notice the lack of response you are having with xmlseclibs.. Would you be interested in trying this library instead? If not; please forget I even tagged you!
