### ISSUE TITLE
Exception when using long serial numbers

### ISSUE THREAD

**Issue by veldenb** [simplesamlphp/xml-security#44]
Hi,

I'm currently running into an issue with long serial numbers.
Works:
`$var = new \SimpleSAML\XMLSecurity\XML\ds\X509SerialNumber('1234567891234567891');`

Gives an exception:
`$var = new \SimpleSAML\XMLSecurity\XML\ds\X509SerialNumber('12345678912345678912');`
`SchemaViolationException: Expected an integerish value. Got: string`

The fix seems to be trivial to replace `Assert::integerish()` with `Assert::numeric()` in `SimpleSAML\XMLSecurity\XML\ds\X509SerialNumber::validateContent()`.

Can this be changed?

Thanks in advance!

**Comment by tvdijen** [comment]
Fixed & v1.0.8 tagged!
Thanks for using this library, and please let us know if you run into anything. We appreciate your feedback!

**Comment by veldenb** [comment]
Thanks for the quick response! :)
